
pipeline {

    agent any
    environment {
        dotnet = '\"C:\\Program Files\\dotnet\\dotnet.exe\"'
        msdeploy= '\"C:\\Program Files (x86)\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe\"'
    }

    stages {
        
        stage ('Clean workspace') {
            steps {
                cleanWs()
            }
        }
        
        stage ('Verifying toolsets') {
            steps {
                bat '''
                    git
                    %dotnet% --info
                '''
            }
        }

        stage('Checkout Stage') {
            steps {
                //git credentialsId: '1efe5f58-ab50-4dbb-8aff-7cba115d80aa', url: 'https://github.com/beglinazarov/SampleDotnetWebApi.git', branch: 'master'

                checkout([  
                    $class: 'GitSCM', 
                    branches: [[name: 'refs/heads/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '']], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [[credentialsId: '1efe5f58-ab50-4dbb-8aff-7cba115d80aa', url: 'https://github.com/beglinazarov/SampleDotnetWebApi.git']]
                ])
            }
        }

        stage("DotNet Restoring Packages") {
            steps {
                bat '%dotnet% restore "%WORKSPACE%\\SampleDotnetWebApi.csproj"'
            }
        }

        stage('DotNet Build & Publish ') {
            steps {
                bat '%dotnet% build "%WORKSPACE%\\SampleDotnetWebApi.csproj"' 
            }
        }

        stage('DotNet Release Test') {
            steps {
                bat '%dotnet% publish -c release -o "%WORKSPACE%\\SampleDotnetWebApi\\Releases\\WebApi_v%BUILD_ID%" --no-restore' 
            }
        }
        stage('Deploy Stage | Dotnet WebApi deploy to IIS via msdeploy') {
            environment {
                    //Kaynak kodun içerisindeki projenin ismi
                    projectName = 'SampleDotnetWebApi'

                    //Kaynak kodun publish edileceği dizin
                    publishedPath = 'SampleDotnetWebApi\\Releases\\WebApi_v%BUILD_ID%'

                    //Hedef makinesindeki IIS'de tanımlı olan sitenizin ismi
                    iisApplicationName = 'SampleDotnetWebApi'

                    //Hedef makinesindeki IIS'de tanımlı olan sitenizin dizini
                    iisApplicationPath = 'C:\\inetpub\\SampleDotnetWebApi'

                    //Hedef makinesinin IP'si
                    targetServerIP = 'KurumsalTest'
                }
            steps {
                //Deploy application on IIS
                //bat 'net stop "w3svc"' 
                //bat '%msdeploy% -verb:sync -source:iisApp="${WORKSPACE}\\${env.publishedPath}"  -dest:iisApp="${iisApplicationName}",ComputerName="https://${targetServerIP}:8172/msdeploy.axd",UserName="serviceaccount",Password="wBdL2azuw3333C556P",AuthType="Basic" -allowUntrusted -enableRule:AppOffline'
                //bat '%msdeploy% -verb:sync -source:iisApp="${publishedPath}\\${env.publishedPath}_v%BUILD_ID%" -dest:-dest:iisApp="${iisApplicationName} -skip:objectName=filePath, AuthType="Basic" -enableRule:DoNotDelete -allowUntrusted=true'
                // withCredentials([usernamePassword(credentialsId: 'iis-cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) { 
                //     bat """ 
                //         %msdeploy%  -verb:sync  -source:iisApp="${WORKSPACE}\\${publishedPath}" -enableRule:AppOffline -dest:iisApp="${iisApplicationName}", computerName="https://${targetServerIP}:8172/msdeploy.axd", UserName="$USERNAME",Password="$PASSWORD", AuthType="Basic" -allowUntrusted
                //         """
                // }

                withCredentials([usernamePassword(credentialsId: 'iis-cred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) { bat """ "C:\\Program Files (x86)\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe" -verb:sync -source:iisApp="${WORKSPACE}\\${publishedPath}" -enableRule:AppOffline -dest:iisApp="${iisApplicationName}",ComputerName="https://${targetServerIP}:8172/msdeploy.axd?site=${iisApplicationName}",UserName="KURUMSALTEST\\$USERNAME",Password="$PASSWORD",AuthType="Basic" -allowUntrusted=true -skip:Directory="App_Data" """}


                //bat 'net start "w3svc"'
            }
        }   
    }
}
