
pipeline {

    agent any
    environment {
        dotnet = '\"C:\\Program Files\\dotnet\\dotnet.exe\"'
        msdeploy= '\"C:\\Program Files (x86)\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe\"'
    }

    stages {
        
        stage ('Clean workspace') {
            steps {
                cleanWs()
            }
        }
        
        stage ('Verifying toolsets') {
            steps {
                bat '''
                    git
                    %dotnet% --info
                '''
            }
        }

        stage('Checkout Stage') {
            steps {
                git credentialsId: '1efe5f58-ab50-4dbb-8aff-7cba115d80aa', url: 'https://github.com/beglinazarov/SampleDotnetWebApi.git', branch: 'master'
            }
        }

        stage("DotNet Restoring Packages") {
            steps {
                bat '%dotnet% restore "%WORKSPACE%\\SampleDotnetWebApi.csproj"'
            }
        }

        stage('DotNet Build & Publish ') {
            steps {
                bat '%dotnet% build "%WORKSPACE%\\SampleDotnetWebApi.csproj"' 
            }
        }

        stage('DotNet Release Test') {
            steps {
                bat '%dotnet% publish -c release -o "C:\\Releases\\WebApi_v%BUILD_ID%" --no-restore' 
            }
        }
        stage('Deploy Stage | Dotnet WebApi deploy to IIS via msdeploy') {
            steps {
                //Deploy application on IIS
                bat 'net stop "w3svc"'
                bat '%msdeploy% -verb:sync -source:package="C:\\Releases\\WebApi_v%BUILD_ID%" -dest:auto -setParam:"IIS Web Application Name"="SampleDotnetWebApi" -skip:objectName=filePath,absolutePath=".\\\\PackagDemoeTmp\\\\Web.config$" -enableRule:DoNotDelete -allowUntrusted=true'
                bat 'net start "w3svc"'
            }
        }   
    }
}
